name: Analyze

on:
  pull_request:
  push:

jobs:
  psalm:
    strategy:
      matrix:
        php: [8.1]

    name: Psalm, PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none

      - name: Determine Composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies installed with Composer
        uses: actions/cache@v3.2.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: php-${{ matrix.php }}-composer-

      - name: Install dependencies with composer
        run: composer install --no-interaction --optimize-autoloader

      - name: Static analysis
        run: composer psalm -- --stats --long-progress --output-format=github --php-version=${{ matrix.php }}
